export const components = [
  'aeria-accordion',
  'aeria-bare-button',
  'aeria-button',
  'aeria-card',
  'aeria-checkbox',
  'aeria-crud',
  'aeria-file',
  'aeria-form',
  'aeria-grid',
  'aeria-icon',
  'aeria-info',
  'aeria-input',
  'aeria-main',
  'aeria-options',
  'aeria-panel',
  'aeria-search',
  'aeria-select',
  'aeria-switch',
  'aeria-table',
  'aeria-tabs',
]

